apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-second
  name: nginx-second
  namespace: namespace-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-second
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-second
    spec:
      containers:
      - image: nginx:1.26.2
        imagePullPolicy: Always
        name: nginx-second
        ports:
        - containerPort: 80
        resources: {}
status: {}
