apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-first-svc
  namespace: namespace-1
  labels:
    app: nginx-first
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-first
  type: ClusterIP
