apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-second-svc
  namespace: namespace-2
  labels:
    app: nginx-second
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-second
  type: ClusterIP
